### ISSUE TITLE
March 26 morning session

### ISSUE THREAD

**Issue by mariordgez** [notlfish/times-article-clone#2]

**Comment by mariordgez** [comment]
Nice and clean semantic HTML, looks very similar to original article.

**Comment by IbrohimRasulov** [comment]
I recommend you to use  this sample README.md template on the link https://github.com/microverseinc/readme-template

**Comment by bettercallsully** [comment]
Nice semantic HTML, could take a couple of pages out of your book for learning purposes.

**Comment by omar-labana** [comment]
You should get familiar with npm and configure terminal linting on save or within your code editor. Great work👍.
